spring.data.mongodb.uri=mongodb://localhost:27017/tiendasana
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#Mail
simplejavamail.smtp.host=smtp.gmail.com
simplejavamail.smtp.port=587
simplejavamail.smtp.username=tiendasana74@gamil.com
simplejavamail.smtp.password=jejb oomj ubpq ujvg
simplejavamail.smtp.transport.strategy=SMTP_TLS
spring.mail.properties.mail.smtp.auth=true
simplejavamail.debug=true
#Swagger
springdoc.use-management-port=true
management.server.port=8082
management.endpoints.web.exposure.include=*