#Mail
simplejavamail.smtp.host=smtp.gmail.com
simplejavamail.smtp.port=587
simplejavamail.smtp.username=tiendasana74@gmail.com
simplejavamail.smtp.password=jejb oomj ubpq ujvg
simplejavamail.smtp.transport.strategy=SMTP_TLS
spring.mail.properties.mail.smtp.auth=true
simplejavamail.debug=true

#Swagger
springdoc.use-management-port=true
management.server.port=8082
logging.level.org.springframework.boot.context.properties.bind=TRACE

#Google sheets
google.sheets.spreadsheet-id=1rQGF-AGG-kXx1dtS0Va2CQkzHYHXQI8OY5r9NDd3PI8

# Exponer endpoints de actuator incluyendo prometheus
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.security.enabled=false

# Configurar métricas
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true

# Nombre de la aplicación
spring.application.name=tienda-sana

# Para Tomcat (por defecto)
server.tomcat.threads.max=50
# si tus operaciones son lentas (como llamadas a Google Sheets).
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=20
# Un valor más bajo hace que falle más rápido bajo carga extrema,
# lo cual puede ser preferible a que muchas solicitudes esperen indefinidamente
# y consuman recursos del lado del cliente y del servidor.